#!/bin/bash

USAGE() {
    echo "$0 qemu_image [qemu_data_image] target_dir"
    exit 1
}

if [ $# == 2 ]; then
    qemu_image=$1
    qemu_data_image=
    target_dir=$2

    if [ ! -f "$qemu_image" -o ! -d "$target_dir" ]; then
        USAGE
    fi
elif [ $# == 3 ]; then
    qemu_image=$1
    qemu_data_image=$2
    target_dir=$3

    if [ ! -f "$qemu_image" -o ! -f "$qemu_data_image" -o ! -d "$target_dir" ]; then
        USAGE
    fi
else
    USAGE
fi
machine_name="LiRE-$RANDOM"


temp_dir=$(mktemp -d)
vmdk_image="$temp_dir/LiRE$CONFIG_LIRE_VERSION.vmdk"
vmdk_data_image="$temp_dir/LiRE_data.vmdk"
VBoxManage convertfromraw $qemu_image $vmdk_image

if [ -n "$qemu_data_image" ]; then
    VBoxManage convertfromraw $qemu_data_image $vmdk_data_image
fi

VBoxManage createvm --name $machine_name --ostype "Linux_64" --register
VBoxManage modifyvm $machine_name --memory 2048 --cpus 4 --nic1 intnet
VBoxManage storagectl $machine_name --name "SATA Controller" --add sata --portcount 2
VBoxManage storageattach $machine_name --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium $vmdk_image

if [ -n "$qemu_data_image" ]; then
    VBoxManage storageattach $machine_name --storagectl "SATA Controller" --port 1 --device 0 --type hdd --medium $vmdk_data_image
fi

VBoxManage export $machine_name --output "$target_dir/LiRE$CONFIG_LIRE_VERSION.ovf"
#VBoxManage storageattach $machine_name --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium none

#if [ -n "$qemu_data_image" ]; then
#    VBoxManage storageattach $machine_name --storagectl "SATA Controller" --port 1 --device 0 --type hdd --medium none
#fi

VBoxManage unregistervm $machine_name --delete

rm -r $temp_dir
sed -i "s/$machine_name/LiRE$CONFIG_LIRE_VERSION/g" "$target_dir/LiRE$CONFIG_LIRE_VERSION.ovf"

