#!/bin/sh

export PATH=/usr/bin:/bin:/sbin:/usr/sbin
if [[ "`whoami`" == "root" ]]
then 
	export PS1="\\u@\\h :\\W# "
else
	export PS1="\\u@\\h :\\W> "
fi

alias la='ls -lah'
alias ll="ls -lh"
alias dir="ls -l"
alias l="ls -alF"
alias md="mkdir -p"
alias ..="cd .."
alias o="less"

export PYTHONHOME=/
export ROS_ROOT=/usr
export ROS_HOME=/tmp
export ROS_MASTER_URI=http://localhost:11311
export ROS_PYTHON_LOG_CONFIG_FILE=/etc/ros/python_logging.conf
