#! /bin/sh


. /etc/lire.conf
################################################
#
# Add and start your skripts here
#
# -> lire.conf has been loaded
#
################################################

echo ""
echo "LiRE custom start ... "
echo ""

echo "mounting /dev/sda5 on /data"
mount /dev/sda5 /data
