#! /bin/sh


. /etc/lire.conf
################################################
#
# Add and start your skripts here
#
# -> lire.conf has been loaded
#
################################################

echo ""
echo "LiRE custom start ... "
echo ""

echo "starting software in /PRODUKTIV/active"
cd /PRODUKTIV
./active

